### ISSUE TITLE
File 实现的问题

### ISSUE THREAD

**Issue by leohawke** [lhmouse/MCF#6]
NtDelayExecution 的第二个参数为nullptr  在Win10 上会返回无效的内存访问错误

**Comment by lhmouse** [comment]
尝试传入 LARGE_INTEGER{INT64_MIN}。
另外不确定 Win10 对此 syscall 是否有更改。

**Comment by lhmouse** [comment]
This API is highly undocumented. But as evidenced by [KeDelayExecutionThread()](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551986(v=vs.85).aspx),the second parameter is very likely to be non-optional.

Patch coming.
