### ISSUE TITLE
3 suggestions for optimizing strlen further

### ISSUE THREAD

**Issue by CarterLi** [lhmouse/MCF#7]
1. Use `_mm_setzero_si128()` instead of `_mm_set1_epi8(0)`( when 0 cannot be recognised as a constant ), which means don't forward `strlen` to `memchr` and friends.  
`_mm_set1_epi8(c)` means `movd` followed by `pshufd` or even worse. `_mm_setzero_si128()` simply means `pxor`.  
Yes GCC 7.1 does generate two functions for `_mm_set1_epi8(0)` as a special case, which was a surprise. But ( I suppose ) most compilers won't.

1. Use `_mm_loadu_si128` for aligning pointers  
You may load unaligned 16-n bytes completely using `_mm_loadu_si128` instead of writing a loop. This improves performance greatly when the buffer is unaligned and small. It helps more after migrating to avx.  

1. Unroll loops manually.  
It's worth doing to make CPU executes them in parallel. Note twice is enough because in this case, 2 masks generated by `_mm_movemask_epi8` ( 2 bytes once ) can be stored into one register (-m32) and then being scanned by bsf or tzcnt ( aka rep bsf ).

Test cases (use online compiler for fair):

1. https://ideone.com/1vwHi3  
Aligned large buffer: about 10% improvement.

1. https://ideone.com/5UExGr
Unaligned small buffer: huge improvement.

1. https://ideone.com/vc8QIF
Unaligned small buffer ( only 1 byte to scan ): almost the same, but still better.

**Comment by lhmouse** [comment]
1. That was what I did before the introduction of `_MCFCRT_rawmemchr()`, at which point _maintainability_ was considered crucial, surpassing _performance_. If no inline version of `strlen()` is emitted by the compiler (that is, a call to external function is emitted), the performance improvement gained by `_mm_setzero_si128()` is basically counteracted by the degradation introduced by the function call.

2. If the NTMBS resides in the last 15 bytes of a page, load of 16 bytes via `_mm_loadu_si128()` would read from two pages, which is prohibited apparently, because if the second page is unreadable, a fault takes place.

3. On my CPU (Xeon E3 1230v3) unrolling loops manually doesn't seem to have any effect on performance. It doesn't make things better or worse. I believe the bottleneck of performance is memory loads here. Loading two `XMMWORD`s in a row also requires aligning the pointer to a 32-byte boundary (see `_MCFCRT_rawwmemchr()` for how to do it) which also adds some overhead before the main scan loop.

**Comment by CarterLi** [comment]
OK I understand what you said.

But I don't understand following comments:  
```c++
// 如果 rp 是对齐到字的，就不用考虑越界的问题。
// 因为内存按页分配的，也自然对齐到页，并且也对齐到字。
// 每个字内的字节的权限必然一致。
```  
I understand `因为内存按页分配的，也自然对齐到页，并且也对齐到字。每个字内的字节的权限必然一致。` which means `if (p % PAGE_SIZE == 0) assert(p % 2 == 0);`.  
But it has nothing to do with `如果 rp 是对齐到字的，就不用考虑越界的问题。` because you can't say `if (p % 2 == 0) assert(p % PAGE_SIZE == 0);`

**Comment by CarterLi** [comment]
We may optimise opinion 2 in `memchr` when buf size is known to be larger then `sizeof(__m128i)`

**Comment by CarterLi** [comment]
I fixed my code as global arrays are not always aligned to 16 boundary.

Now I force the pointer aligned to 16 but 32  
Result (https://ideone.com/DH53Ok):  
```
pstart % 32 == 0: 0

_MCFCRT_rawmemchr: 45381160, count = 984000000
myStrlen2: 35299546, count = 984000000
Dur2 / Dur1 = 77.784583%

_MCFCRT_rawmemchr: 44739220, count = 1968000000
myStrlen2: 35402596, count = 1968000000
Dur2 / Dur1 = 79.131009%

_MCFCRT_rawmemchr: 44699319, count = 2952000000
myStrlen2: 35502374, count = 2952000000
Dur2 / Dur1 = 79.424866%

_MCFCRT_rawmemchr: 45870700, count = 3936000000
myStrlen2: 34643301, count = 3936000000
Dur2 / Dur1 = 75.523811%

_MCFCRT_rawmemchr: 43733002, count = 4920000000
myStrlen2: 34571982, count = 4920000000
Dur2 / Dur1 = 79.052387%

_MCFCRT_rawmemchr: 45433984, count = 5904000000
myStrlen2: 33953518, count = 5904000000
Dur2 / Dur1 = 74.731545%

_MCFCRT_rawmemchr: 44407826, count = 6888000000
myStrlen2: 34814665, count = 6888000000
Dur2 / Dur1 = 78.397589%

_MCFCRT_rawmemchr: 45279426, count = 7872000000
myStrlen2: 35037041, count = 7872000000
Dur2 / Dur1 = 77.379605%

_MCFCRT_rawmemchr: 47830138, count = 8856000000
myStrlen2: 34591204, count = 8856000000
Dur2 / Dur1 = 72.320937%

_MCFCRT_rawmemchr: 44812364, count = 9840000000
myStrlen2: 35125851, count = 9840000000
Dur2 / Dur1 = 78.384285%

_MCFCRT_rawmemchr: 44791256, count = 10824000000
myStrlen2: 34397699, count = 10824000000
Dur2 / Dur1 = 76.795567%

_MCFCRT_rawmemchr: 43723069, count = 11808000000
myStrlen2: 34815266, count = 11808000000
Dur2 / Dur1 = 79.626766%

_MCFCRT_rawmemchr: 47479250, count = 12792000000
myStrlen2: 34251289, count = 12792000000
Dur2 / Dur1 = 72.139490%

_MCFCRT_rawmemchr: 45069577, count = 13776000000
myStrlen2: 35345654, count = 13776000000
Dur2 / Dur1 = 78.424641%

_MCFCRT_rawmemchr: 45881140, count = 14760000000
myStrlen2: 34020104, count = 14760000000
Dur2 / Dur1 = 74.148341%

_MCFCRT_rawmemchr: 43914279, count = 15744000000
myStrlen2: 36402589, count = 15744000000
Dur2 / Dur1 = 82.894653%

_MCFCRT_rawmemchr: 45499743, count = 16728000000
myStrlen2: 36343264, count = 16728000000
Dur2 / Dur1 = 79.875757%

_MCFCRT_rawmemchr: 45132791, count = 17712000000
myStrlen2: 34604413, count = 17712000000
Dur2 / Dur1 = 76.672442%

_MCFCRT_rawmemchr: 45179365, count = 18696000000
myStrlen2: 37498545, count = 18696000000
Dur2 / Dur1 = 82.999274%

_MCFCRT_rawmemchr: 45850165, count = 19680000000
myStrlen2: 36080412, count = 19680000000
Dur2 / Dur1 = 78.692000%
```

I got more than 20% performance boost.

**Comment by lhmouse** [comment]
The third paragraph shall be acceptable.

For small strings that get cache hits frequently, it decreases the execution time by about 9%. For large strings that gets cache misses constantly, there is little benefit.

Modified code: <http://paste.ubuntu.com/25154329/>

```text
// #define N_CHARS     1000000000u
// #define N_LOOPS     100u
_MCFCRT_rawmemchr()    : 7098.000000 ms
_MCFCRT_rawmemchr_ddq(): 7051.000000 ms
```

```text
// #define N_CHARS     100u
// #define N_LOOPS     1000000000u
_MCFCRT_rawmemchr()    : 4430.000000 ms
_MCFCRT_rawmemchr_ddq(): 4088.000000 ms
```

**Comment by lhmouse** [comment]
> We may optimise opinion 2 in memchr when buf size is known to be larger then sizeof(__m128i)
> Or we may detect page fault by p % 4096 + 15 < 4096, am I correct?

Adding a branch here for the corner case is **nothing** better, as the overhead of scanning bytewise (without the branch above) is constant.

**Comment by CarterLi** [comment]
I get better performance by changing 31 to 15

**Comment by CarterLi** [comment]
Now I might know the necessarity of accessing aligned memory thank you for your explaination (although not very patient :)  
There is another question: _does_ the stdandard permits reading out-of-bound memory (I mean UB) though it wont result in seg fault?

**Comment by lhmouse** [comment]
> There is another question I had for long time: does the stdandard permits reading out-of-bound memory indeed (I mean UB) though it wont result in seg fault?

Yes, as long as the standard doesn't care about `volatile`-unqualified objects:

### WG14 N1570
> **5.1.2.3 Program execution**
> 6 The least requirements on a conforming implementation are:
> — Accesses to volatile objects are evaluated strictly according to the rules of the abstract
> machine.
> — At program termination, all data written into files shall be identical to the result that
> execution of the program according to the abstract semantics would have produced.
> — The input and output dynamics of interactive devices shall take place as specified in
> 7.21.3. The intent of these requirements is that unbuffered or line-buffered output
> appear as soon as possible, to ensure that prompting messages actually appear prior to
> a program waiting for input.
> This is the _observable behavior_ of the program

**Comment by lhmouse** [comment]
The same optimization can be applied to `stpcpy()`, `rawmemchr()`, `memchr()`, `strchr()`, and their wide counterparts. Please review.

I am doubtful about applying it to `strcmp()` etc.

**Comment by lhmouse** [comment]
I am closing this issue. Please move further discussion to the PR above #8 .
